name: SonarQube Analysis
on:
  push:
    branches: [master, develop]
    pull_request:
      types: [opened, synchronize, reopened]

permissions:
  contents: read

jobs:
  sonarqube:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: SonarQube Scan
        run: |
          mvn clean verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
            -Dsonar.projectKey=quality-measurement \
            -Dsonar.projectName='Quality measurement' \
            -Dsonar.host.url=http://sonaq.sihsalus.gidistest:9000 \
            -Dsonar.token=sqp_151f272aa151d15fe173049abd11cd6cbe34959b \
            -Dsonar.qualitygate.wait=true \
            -Dsonar.qualitygate.timeout=300
